apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deck
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dhairya-itp/color-block-gitops.git
    targetRevision: main
    path: deck
  destination:
    server: https://kubernetes.default.svc
    namespace: deck
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
